package com.example.Hotel.entity.task;

import java.time.LocalDate;
import java.time.LocalTime;

import com.example.Hotel.entity.room.Room;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import lombok.Getter;
import lombok.Setter;

@Entity
@Setter
@Getter
public class Task {
    
    @Id
    @GeneratedValue(strategy =  GenerationType.IDENTITY)
    Long taskId;

    LocalDate dueDate;
    LocalTime dueTime;

    @ManyToOne // Many tasks can be associated with one task configuration
    @JoinColumn(name = "task_config_id") // Assuming there is a foreign key column in the Task table referencing TaskConfig
    TaskConfig taskConfig;

    String priority;

    @ManyToOne // Many tasks can be associated with one room
    @JoinColumn(name = "room_id") // Assuming there is a foreign key column in the Task table referencing Room
    Room room;

    String status;
    boolean autoGenerated;// yes/ no

    public Task(LocalDate dueDate, LocalTime dueTime, TaskConfig taskConfig, String priority, Room room,
        String status, boolean autoGenerated)
    {
        this.dueDate = dueDate;
        this.dueTime = dueTime;
        this.taskConfig = taskConfig;
        this.priority = priority;
        this.room = room;
        this.status = status;
        this.autoGenerated = autoGenerated;
    }

    public Task()
    {

    }
    

}
