package com.example.Hotel.repository.task;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.example.Hotel.entity.room.Room;
import com.example.Hotel.entity.task.Task;
import com.example.Hotel.entity.task.TaskConfig;

import java.util.List;
import java.util.Optional;
import java.time.LocalDate;



@Repository
public interface TaskRepository extends JpaRepository<Task, Long>{
    List<Task> findByStatus(String status);
    List<Task> findByDueDate(LocalDate dueDate);
    List<Task> findByDueDateAndPriority(LocalDate dueDate, String priority);
    List<Task> findByPriority(String priority);
    List<Task> findByAutoGenerated(Boolean generatedType);
    List<Task> findByRoomAndTaskConfigAndStatusNot(Room room, TaskConfig taskConfig, String status);
    void deleteByRoomAndTaskConfig(Room room, TaskConfig taskConfig);
    Optional<Task> findById(Long id);
    List<Task> findByRoom(Room room);
    List<Task> findByStatusAndRoom(String status, Room room);
    List<Task> findByRoomOrderByDueDateAsc(Room room);
}
